"""Build a named variant of the public pipeline from our canonical copy.

    python -m scripts.kaggle_variant --list
    python -m scripts.kaggle_variant bench --push
    python -m scripts.kaggle_variant nocoat raptor2 --push

The notebook under `kaggle/public-d4/` is 254 KB of someone else's code, and every
ablation of it differs by a few dozen lines. Committing one copy per ablation would put
a megabyte of near-duplicates in git and let them drift apart. So the patches live here
and the notebooks are generated, the way the atlas builders are in git and their pages
are not.

Each patch asserts that it matched. A rename upstream then stops the build instead of
silently producing the unmodified pipeline under a name that claims otherwise — which is
the failure that matters, because it scores and looks like a result.
"""

from __future__ import annotations

import argparse
import ast
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "kaggle" / "public-d4"
OWNER = "mathysgouverneur"

#: The pair that runs together on one GPU and shares its decoded windows, so the second
#: is nearly free. Everything else is scheduled singly and costs a full pass.
SHARED_PAIR = ("maxspan-v5", "maxspan-v5-reverse")


def _edit(cells: list, needle: str, replace, label: str, expect: int = 1) -> None:
    """Apply `replace` to every code cell containing `needle`, insisting on a count."""

    hits = 0
    for cell in cells:
        if cell["cell_type"] != "code":
            continue
        source = "".join(cell["source"])
        if needle not in source:
            continue
        cell["source"] = [replace(source)]
        hits += 1
    if hits != expect:
        raise SystemExit(
            f"patch {label!r} matched {hits} cell(s), expected {expect}. The upstream "
            f"notebook has moved; read it before building anything named after it.")


def patch_bench(nb: dict, n: int = 120) -> None:
    """Run on a cohort big enough to time, in a commit run instead of a submission.

    A commit run sees three studies and a scored run sees 1322, with nothing between.
    Three are all fixed cost, so they cannot price an ablation; 1322 can, but costs a
    submission and hours. Both `find_root` and `find_test_root` honour `RSNA_COMP_ROOT`,
    so a cohort of training studies — symlinked, never copied — makes a commit run
    measure what a scored run would.

    Two runs then separate the two costs: `t(3) = fixed + 3·per` and
    `t(n) = fixed + n·per` give both, and `t(1322)` follows.

    It prices a variant. It cannot score one: these studies trained every public model
    in the pipeline, so any AUC over them is meaningless.
    """

    cell = f'''# ===================== BENCH — a cohort big enough to time =====================
# Generated by scripts/kaggle_variant.py. N stays above 48 on purpose:
# `RSNA_PARALLEL_COAT_READERS` defaults to parallel at or below that, and the scored run
# is serial, so a smaller cohort would measure a pipeline that never runs.
import os
import shutil
from pathlib import Path

import pandas as pd

BENCH_N = int(os.environ.get("BENCH_N", "{n}"))
_src = Path("/kaggle/input/competitions/rsna-knee-abnormality-detection")
if not _src.is_dir():
    _src = Path("/kaggle/input/rsna-knee-abnormality-detection")
_bench = Path("/kaggle/tmp/bench")
shutil.rmtree(_bench, ignore_errors=True)
(_bench / "test_series").mkdir(parents=True)

_train = pd.read_csv(_src / "train.csv", dtype={{"StudyInstanceUID": str}})
_series = pd.read_csv(_src / "train_series.csv", dtype={{"StudyInstanceUID": str}})
_have = {{p.name for p in (_src / "train_series").iterdir() if p.is_dir()}}
_ids = [s for s in _train.StudyInstanceUID if s in _have][:BENCH_N]
assert len(_ids) == BENCH_N, f"only {{len(_ids)}} studies available"

pd.DataFrame({{"StudyInstanceUID": _ids}}).to_csv(_bench / "test.csv", index=False)
_series[_series.StudyInstanceUID.isin(_ids)].to_csv(_bench / "test_series.csv", index=False)
_sample = pd.read_csv(_src / "sample_submission.csv")
_sub = pd.DataFrame({{"StudyInstanceUID": _ids}})
for _c in [c for c in _sample.columns if c != "StudyInstanceUID"]:
    _sub[_c] = 0.5
_sub.to_csv(_bench / "sample_submission.csv", index=False)
for _s in _ids:
    (_bench / "test_series" / _s).symlink_to(_src / "train_series" / _s)

# `plan_cache` sizes the DINO cache from the real train and test counts, so the genuine
# tables are linked rather than trimmed ones: the cohort changes what is scored, not how
# the pipeline dimensions itself.
for _name in ("train.csv", "train_series.csv"):
    (_bench / _name).symlink_to(_src / _name)

os.environ["RSNA_COMP_ROOT"] = str(_bench)
print(f"[bench] cohort of {{BENCH_N}} training studies at {{_bench}}", flush=True)
'''
    nb["cells"].insert(0, {"cell_type": "code", "execution_count": None,
                           "metadata": {}, "outputs": [], "source": [cell]})


def patch_raptor2(nb: dict) -> None:
    """Drop the two Raptor arms that do not share their decoding — 4 arms become 2.

    Raptor is the heaviest stage by a wide margin — 62+62+62+42 forward passes of a
    CoAtNet at 384 px per study, against six windows for the DINO ensemble. The two arms
    scheduled singly on the second GPU each cost a full independent pass; the surviving
    pair runs together and shares its decoded windows.

    The scheduler addresses arms by the positions they held in the full list, in three
    places, so shortening the list breaks it three times. All three are rewritten to go
    by name.
    """

    cells = nb["cells"]
    _edit(cells, "ARMS = [", lambda s: s.replace(
        "ARMS = [",
        "# TRIMMED: the two arms scheduled singly, each a full independent pass. The\n"
        "# survivors share their decoded windows. `weights /= weights.sum()` renormalises\n"
        "# downstream and nothing asserts a count.\n"
        "_ARMS_DROP = ['native384dense-v10', 'native384-v8']\n"
        "ARMS = [", 1).replace(
        "\ndef build_backbone(",
        "\nARMS = [a for a in ARMS if a['name'] not in _ARMS_DROP]\n"
        "print('[trim] Raptor arms kept: ' + ', '.join(a['name'] for a in ARMS), flush=True)\n"
        "\n\ndef build_backbone(", 1), "trim:arms")

    _edit(cells, "first, reverse = arms[0], arms[2]", lambda s: s.replace(
        "        first, reverse = arms[0], arms[2]",
        f"        _pair = [a for a in arms if a['name'] in {SHARED_PAIR!r}]\n"
        "        _at = {a['name']: i for i, a in enumerate(arms)}\n"
        "        first, reverse = _pair[0], _pair[1]").replace(
        "outputs[0][study_index]", "outputs[_at[first['name']]][study_index]").replace(
        "outputs[2][study_index]", "outputs[_at[reverse['name']]][study_index]"),
        "trim:pair")

    _edit(cells, "run_single(1, torch.device('cuda:1'))", lambda s: s.replace(
        """    def gpu_one():
        with torch.cuda.device(1):
            run_single(1, torch.device('cuda:1'))
            run_single(3, torch.device('cuda:1'))""",
        "    def gpu_one():\n"
        "        with torch.cuda.device(1):\n"
        "            for _index, _arm in enumerate(arms):\n"
        f"                if _arm['name'] in {SHARED_PAIR!r}:\n"
        "                    continue\n"
        "                run_single(_index, torch.device('cuda:1'))"), "trim:scheduler")


def patch_nocoat(nb: dict) -> None:
    """Drop all four CoAtNet readers — 55 % of the pipeline's compute, worth +0.001.

    They are subprocesses, each reloading its own weights, and they run strictly one
    after another on any cohort over 48 studies — `RSNA_PARALLEL_COAT_READERS` defaults
    to off above that. With none of them `_members` stays empty and the code takes its
    own documented branch: "no CoAt family member available; public Raptor retained".
    """

    _edit(nb["cells"], "_run_residual_reader, _run_global96_reader", lambda s: s.replace(
        """    if _parallel_pairs:
        for _pair in ((_run_residual_reader, _run_d4_reader),
                      (_run_global96_reader, _run_repairv1_reader)):
            with _KeThreadPool(max_workers=2) as _pool:
                _jobs = [_pool.submit(_reader) for _reader in _pair]
                for _job in _jobs:
                    _job.result()
    else:
        for _reader in (_run_residual_reader, _run_global96_reader,
                        _run_d4_reader, _run_repairv1_reader):
            _reader()""",
        "    # TRIMMED: no CoAt reader runs; the empty-family branch keeps public Raptor.\n"
        "    print('[trim] CoAt readers skipped; public Raptor stands', flush=True)"),
        "coat")


#: How much of its column each expert takes from the host, as ranks. 0.5 is what was
#: measured against **our own** wide model out of fold: +0.0259 of macro against the host
#: alone, where handing the column over outright is worth +0.0159.
#:
#: That host scored 0.835 internally; this one scores 0.943 on the leaderboard. A
#: stronger host deserves more weight, so 0.5 is probably too generous here — but tuning
#: it would mean fitting a constant on one submission, which is how a leaderboard teaches
#: you its noise. It is left where it was measured, and moved once there is a reading.
#:
#: For scale: the author's own graft of a foreign leg uses 0.45 across all twelve
#: columns. Ours is 0.5 across seven, which is less total mass, not more.
EXPERT_BLEND = 0.5

GRAFT_CELL = '''# ===================== OUR LEG — the experts, grafted on =====================
# Generated by scripts/kaggle_variant.py. The public pipeline has written submission.csv;
# seven of its twelve columns are now re-ordered by per-pathology experts reading a 48 mm
# crop centred on a predicted landmark. Nothing upstream has that view: `landmark` and
# `roi` appear zero times in those 4744 lines, and every model there crops the middle of
# the picture at 130-140 mm.
#
# The grammar is the pipeline's own — a constant weight, in rank space, with the host
# kept wherever our side could not read a study.
import os
import sys
import tempfile
import zipfile
from pathlib import Path

BLEND = {blend}
INPUT = Path("/kaggle/input")


def _walk(root):
    for current, dirs, files in os.walk(root):
        dirs[:] = [d for d in dirs if d not in ("train_series", "test_series")]
        yield Path(current), dirs, files


def _find_library():
    for current, dirs, files in _walk(INPUT):
        if "config.py" in files and "infer" in dirs:
            return current
    for current, _, files in _walk(INPUT):
        for name in files:
            if name.endswith(".zip") and "rsna" in name:
                target = Path(tempfile.mkdtemp())
                with zipfile.ZipFile(current / name) as archive:
                    archive.extractall(target)
                for inner, inner_dirs, inner_files in os.walk(target):
                    if "config.py" in inner_files and "infer" in inner_dirs:
                        return Path(inner)
    return None


_runs = {{}}
for _current, _, _files in _walk(INPUT):
    if "fold0.pt" in _files and _current.name.startswith(("expert_", "landmark_")):
        _runs[_current.name] = _current
experts = sorted(p for n, p in _runs.items() if n.startswith("expert_"))
landmarks = sorted(p for n, p in _runs.items() if n.startswith("landmark_"))
library = _find_library()
print(f"[ours] library={{library}} experts={{len(experts)}} landmarks={{len(landmarks)}}",
      flush=True)

if library is None or not experts or not landmarks:
    print("[ours] SOFT FAIL: our mounts are incomplete -> public-only stands", flush=True)
else:
    import shutil

    staging = Path(tempfile.mkdtemp())
    os.symlink(library, staging / "rsna")
    sys.path.insert(0, str(staging))

    import pandas as pd
    import torch

    from rsna.infer import run_expert_submission

    shutil.copy2("submission.csv", "/kaggle/working/_public_before_experts.csv")
    root = next((c for c, _, f in _walk(INPUT) if "test.csv" in f), None)
    scratch = "/kaggle/working/roi" if Path("/kaggle/working").is_dir() else None
    # No try/except: a leg that swallows its failure leaves the public file in place and
    # reports success, which is indistinguishable from a graft that did nothing.
    run_expert_submission(
        expert_runs=experts, landmark_runs=landmarks, package=None,
        data_root=root, split="test_series", out="submission.csv",
        scratch=scratch, blend=BLEND, workers=4,
        device="cuda" if torch.cuda.is_available() else "cpu", log=print)

    before = pd.read_csv("/kaggle/working/_public_before_experts.csv")
    after = pd.read_csv("submission.csv")
    moved = [c for c in after.columns[1:] if not before[c].equals(after[c])]
    print(f"[ours] columns the experts re-ordered ({{len(moved)}}): {{moved}}", flush=True)
'''


def patch_experts(nb: dict) -> None:
    """Re-order the seven columns our experts own, after the public pipeline has run.

    Needs `mathysgouverneur/rsna-src` and `mathysgouverneur/rsna-knee-experts` mounted;
    the patch adds both. If either is missing the cell says so and leaves the public
    submission alone, which is the only failure mode that should be quiet.
    """

    nb["cells"].append({"cell_type": "code", "execution_count": None, "metadata": {},
                        "outputs": [], "source": [GRAFT_CELL.format(blend=EXPERT_BLEND)]})


#: RadImageNet is **not** here on purpose. Removing it also removes
#: `globals()['V18_CALIBRATOR_APPLIED']=True`, and that flag is not bookkeeping: the cell
#: that sets it fits a learned linear calibrator over the Rad ranks and folds it into 40 %
#: of several columns. The final checks refuse the run without it, correctly.
#: Named for what they *remove*, not for what they touch: a kernel called
#: `rsna-knee-coat` reads as "the one with CoAt" when it is the one without.
PATCHES = {"bench": patch_bench, "raptor2": patch_raptor2,
           "nocoat": patch_nocoat, "experts": patch_experts}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("patches", nargs="*", help=f"any of {sorted(PATCHES)}")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--out", type=Path, default=None)
    ap.add_argument("--push", action="store_true")
    args = ap.parse_args()

    if args.list or not args.patches:
        for name, fn in PATCHES.items():
            print(f"  {name:<8} {(fn.__doc__ or '').strip().splitlines()[0]}")
        return 0

    unknown = [p for p in args.patches if p not in PATCHES]
    if unknown:
        raise SystemExit(f"unknown patch(es) {unknown}; try --list")

    nb = json.loads((SOURCE / "notebook.ipynb").read_text())
    meta = json.loads((SOURCE / "kernel-metadata.json").read_text())
    for name in args.patches:
        PATCHES[name](nb)
    for cell in nb["cells"]:
        if cell["cell_type"] == "code":
            ast.parse("".join(cell["source"]))

    slug = "rsna-knee-" + "-".join(args.patches)
    out = args.out or Path("/tmp") / slug
    out.mkdir(parents=True, exist_ok=True)
    (out / "notebook.ipynb").write_text(json.dumps(nb, indent=1) + "\n")
    if "experts" in args.patches:
        meta["dataset_sources"] = list(meta["dataset_sources"]) + [
            f"{OWNER}/rsna-src", f"{OWNER}/rsna-knee-experts"]
    meta["id"] = f"{OWNER}/{slug}"
    meta["title"] = "RSNA Knee " + " ".join(args.patches)
    (out / "kernel-metadata.json").write_text(json.dumps(meta, indent=1) + "\n")
    print(f"{slug}: {len(nb['cells'])} cells -> {out}")

    if args.push:
        subprocess.run([sys.executable, "-m", "scripts.kaggle_push",
                        "--kernel-dir", str(out)], cwd=ROOT, check=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
